// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rimrock_api.Data;

namespace rimrock_api.Migrations
{
    [DbContext(typeof(RimRockApiDbContext))]
    [Migration("20190417223134_full-seed")]
    partial class fullseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("rimrock_api.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cost");

                    b.Property<string>("Name");

                    b.Property<int>("RegionID");

                    b.HasKey("ID");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Cost = "$$$$$",
                            Name = "Cliff Creek",
                            RegionID = 1
                        },
                        new
                        {
                            ID = 2,
                            Cost = "$$",
                            Name = "Long Shore",
                            RegionID = 1
                        },
                        new
                        {
                            ID = 3,
                            Cost = "$$$$",
                            Name = "Jerall mountains",
                            RegionID = 1
                        },
                        new
                        {
                            ID = 4,
                            Cost = "$$$",
                            Name = "Big Rock",
                            RegionID = 1
                        },
                        new
                        {
                            ID = 5,
                            Cost = "$",
                            Name = "Little Rocks",
                            RegionID = 1
                        },
                        new
                        {
                            ID = 6,
                            Cost = "$$$$$",
                            Name = "Cliff Barz",
                            RegionID = 2
                        },
                        new
                        {
                            ID = 7,
                            Cost = "$$",
                            Name = "Short Shore",
                            RegionID = 2
                        },
                        new
                        {
                            ID = 8,
                            Cost = "$$$$$",
                            Name = "The Lookout",
                            RegionID = 2
                        },
                        new
                        {
                            ID = 9,
                            Cost = "$$",
                            Name = "Medium Rock",
                            RegionID = 2
                        },
                        new
                        {
                            ID = 10,
                            Cost = "$",
                            Name = "Super Mountain",
                            RegionID = 2
                        },
                        new
                        {
                            ID = 11,
                            Cost = "$",
                            Name = "Super Mountain",
                            RegionID = 2
                        },
                        new
                        {
                            ID = 12,
                            Cost = "$",
                            Name = "Boulder Mountain",
                            RegionID = 3
                        });
                });

            modelBuilder.Entity("rimrock_api.Models.Region", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Greater Seattle"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Eastern Washington"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Oklahoma"
                        });
                });

            modelBuilder.Entity("rimrock_api.Models.Retailer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("RegionID");

                    b.Property<string>("Specialty");

                    b.HasKey("ID");

                    b.ToTable("Retailers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Second Ascents",
                            RegionID = 1,
                            Specialty = "Climbing"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Yeager's",
                            RegionID = 1,
                            Specialty = "Skiing"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Backcountry Essentials",
                            RegionID = 1,
                            Specialty = "Climbing"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Batman's Garage",
                            RegionID = 2,
                            Specialty = "Climbing"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Plank's Ski Shop",
                            RegionID = 2,
                            Specialty = "Skiing"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Rocky Bubbaloo",
                            RegionID = 2,
                            Specialty = "Climbing"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Boulders are Mountains Here",
                            RegionID = 3,
                            Specialty = "Climbing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
